### ISSUE TITLE
Project Assignment

### ISSUE THREAD

**Issue by Phan717** [Phan717/web-design-2-independent-project#18]
Hi Christian,

I managed to get the 100% and most of the errors. I still have one more error, and because of this, Markbot won’t allow me to submit. Could you please help me?
@thatkidmadrid

<img width="800" alt="Screen Shot 2021-12-15 at 21 34 50" src="https://user-images.githubusercontent.com/76163382/146299079-7a081eb7-4fb6-48f9-bd6f-0c11d6bdaa22.png">
<img width="800" alt="Screen Shot 2021-12-15 at 21 36 01" src="https://user-images.githubusercontent.com/76163382/146299083-cf831473-aa6d-47e2-9732-9520b83f91a7.png">

**Comment by thatkidmadrid** [comment]
You just need to include an example of a link inside either a `<main>`, `<section>`, or `<article>`

**Comment by Phan717** [comment]
Thank you. I have done and submitted
